<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index test</title>
    <link rel="stylesheet" href="/res/css/main.css?<?= time() ?>">
    <script type="text/javascript" src="/res/js/app.js?<?= time() ?>" defer></script>
</head>
<body>
    <header class="top-menu">
        <?php require __DIR__ . '/top-menu.phtml'; ?>
    </header>

    <container>
        <aside>
            <?php require __DIR__ . '/category-tree.phtml'; ?>
        </aside>

        <main>
            <div class="sort-container">
                <select id="sort-select">
                    <option value="price" >Дешевші</option>
                    <option value="newest">Новіші</option>
                    <option value="a-z">Алфавітний порядок</option>
                </select>
                
            </div>
            <div id="product-list-container"></div>
            <div id="pagination-container"></div>
            
        </main>
    </container>

    <template id="product-item-template">
        <card class="product-card">
            <h3 class="product-title">{{name}}</h3>
            <img class="product-image" src="{{image_url}}" alt="{{name}}">
            <span class="product-price">{{price}}</span>
            <span class="product-created-at">{{created_at}}</span>
            <button class="product-button" onclick="App.loadProductDetails({{product_id}})">Buy</button>
        </card>
    </template>
    <template id="product-popup-template">
        <div class="product-popup-backdrop"></div>
        <div class="product-popup">
            <h3 class="product-title">{{name}}</h3>
            <img class="product-image" src="{{image_url}}" alt="{{name}}">
            <!--p class="product-description">{{description}}</p-->
            <span class="product-price">{{price}}</span>
        </div>
    </template>
    <template id="product-popup-loading-template">
        <div class="product-popup-backdrop"></div>
        <div class="product-popup">
            <div class="product-popup-loading">Loading product...</div>
        </div>
    </template>

    <footer class="page-footer">
        <small>© 2026 vgalitsky</small>
    </footer>
</body>
</html>